name: ansiwise_example
description: An example plugin serving as a reference implementation for the Ansiwise framework.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.0

dependencies:
  ansiwise_api:
    git:
      url: https://github.com/simetrixch/ansiwise-api.git
      ref: master

dev_dependencies:
  test: ^1.31.2
  lints: ^6.1.0
  ansiwise_checks:
    git:
      url: https://github.com/simetrixch/ansiwise-checks.git
      ref: master
      path: registry
