import 'dart:io';

import 'package:test/test.dart';

import '../../tool/paths.dart';
import '../../tool/release_git.dart';
import '../../tool/release_notes_command.dart';
import '../../tool/release_packages.dart';
import '../../tool/release_report.dart';
import '../../tool/release_tag_filter.dart';
import '../fakes.dart';

/// release-notes — the page says what a consumer has to write to take this release, and the release
/// is marked by the CHANNEL in the tag rather than by the hyphen every tag under this grammar
/// carries.
///
/// **Why the page is written at all.** `gh release create --generate-notes` builds its notes from
/// the pull requests merged between two releases. This repository has none — every commit is a
/// commit on master — so the generated page would carry a compare link and nothing else. And the
/// half a consumer actually needs could not be generated by anybody: these packages produce no file,
/// so what the release hands over is a REF and a PATH per package, read off the tree standing at the
/// tag.
///
/// **What the counter-probes are for.** A page that always said the same thing would pass a check
/// that only looked for a sentence, so the packages listed are planted and the page is held against
/// the plant. And the marking is asserted on all three channels, because a marking read off the
/// text would answer "pre-release" for all three and no single-channel check would notice.
void main() {
  const String url = 'https://github.com/simetrixch/ansiwise-plugins.git';
  final TagFilter filter = TagFilter.ofWorkflow(
    'on:\n'
    '  push:\n'
    '    tags:\n'
    "      - '[0-9]+.[0-9]+.[0-9]+-*'\n",
  );

  ManifestsInMemory twoPackages() => ManifestsInMemory(<String, String>{
    'ansiwise-one/pubspec.yaml': plantedPubspec(
      name: 'ansiwise_one',
      version: '0.2.0',
      dependsOn: <String, PlantedDependency>{'ansiwise_two': (path: 'ansiwise-two', ref: 'master')},
    ),
    'ansiwise-two/pubspec.yaml': plantedPubspec(name: 'ansiwise_two', version: '0.2.0'),
  });

  Future<NotesOutcome> notesOf(
    String tag, {
    Map<String, GitAnswer> answers = const <String, GitAnswer>{},
    ManifestsInMemory? manifests,
  }) => ReleaseNotesCommand(
    git: ScriptedGit(answers: answers),
    manifests: manifests ?? twoPackages(),
    filter: filter,
  ).of(tag);

  group('the page of a first release', () {
    test('tells a consumer the ref and the path of every package standing at the tag', () async {
      final NotesOutcome outcome = await notesOf('0.2.0-beta-20260901120000');

      expect(outcome.isGreen, isTrue, reason: outcome.refusal ?? '');
      for (final String written in <String>[
        'ansiwise_one:',
        'ansiwise_two:',
        'path: ansiwise-one',
        'path: ansiwise-two',
        'ref: 0.2.0-beta-20260901120000',
        'url: $url',
      ]) {
        expect(
          outcome.page,
          contains(written),
          reason:
              'a release carrying no file hands over exactly this, and a page missing half of it '
              'leaves a consumer to guess the other half',
        );
      }
    });

    test('says outright that nothing is attached, so nobody waits for a binary', () async {
      final NotesOutcome outcome = await notesOf('0.2.0-beta-20260901120000');

      expect(outcome.page, contains('Nothing is attached below, and nothing is missing'));
      expect(outcome.page, contains('libraries'));
    });

    test('lists what the tree really holds, and not what somebody last wrote here', () async {
      final NotesOutcome outcome = await notesOf(
        '0.2.0-beta-20260901120000',
        manifests: ManifestsInMemory(<String, String>{
          'ansiwise-thirteenth/pubspec.yaml': plantedPubspec(
            name: 'ansiwise_thirteenth',
            version: '0.2.0',
          ),
        }),
      );

      expect(
        outcome.page,
        contains('path: ansiwise-thirteenth'),
        reason:
            'a package added since the last release reaches the page without anybody remembering '
            'to add it, which is the whole point of walking the tree',
      );
      expect(outcome.page, isNot(contains('ansiwise-one')));
    });

    test('and over THIS repository it lists every package really standing in it', () async {
      final Directory repository = repositoryOf(Directory.current);
      final ReleasedPackages packages = ReleasedPackages.read(PubspecsInRepository(repository));
      final NotesOutcome outcome = await ReleaseNotesCommand(
        git: ScriptedGit(),
        manifests: PubspecsInRepository(repository),
        filter: filter,
      ).of('0.2.0-beta-20260901120000');

      expect(outcome.isGreen, isTrue, reason: outcome.refusal ?? '');
      for (final ManifestState package in packages.manifests) {
        expect(outcome.page, contains('  ${package.declaredName}:'));
        expect(outcome.page, contains('      path: ${package.directory}'));
      }
      expect(
        outcome.page,
        contains('url: ${packages.siblingUrl}'),
        reason:
            'the address is copied out of this tree, because pub reads two spellings of one url as '
            'two sources and a page inventing a second one hands over a pubspec that cannot resolve',
      );
    });

    test('and says the range it read was every commit, because nothing came before', () async {
      final NotesOutcome outcome = await notesOf(
        '0.2.0-beta-20260901120000',
        answers: <String, GitAnswer>{
          'tag --list': const GitAnswer(status: 0, output: '0.2.0-beta-20260901120000\n'),
          'log --format=%s 0.2.0-beta-20260901120000': const GitAnswer(
            status: 0,
            output: 'Let a row fill an address\nTwo exchange kinds\n',
          ),
        },
      );

      expect(outcome.page, contains('because nothing was released before it'));
      expect(outcome.page, contains('- Let a row fill an address'));
      expect(outcome.page, contains('- Two exchange kinds'));
    });
  });

  group('the page of a release that follows another', () {
    test('reads the range between the two, and names it', () async {
      final ScriptedGit git = ScriptedGit(
        answers: <String, GitAnswer>{
          'tag --list': const GitAnswer(
            status: 0,
            output: '0.1.0-alpha-20260801120000\n0.2.0-beta-20260901120000\n',
          ),
          'log --format=%s 0.1.0-alpha-20260801120000..0.2.0-beta-20260901120000': const GitAnswer(
            status: 0,
            output: 'One thing changed\n',
          ),
        },
      );
      final NotesOutcome outcome = await ReleaseNotesCommand(
        git: git,
        manifests: twoPackages(),
        filter: filter,
      ).of('0.2.0-beta-20260901120000');

      expect(outcome.page, contains('## Changes since 0.1.0-alpha-20260801120000'));
      expect(outcome.page, contains('- One thing changed'));
      expect(
        git.spelled,
        contains('log --format=%s 0.1.0-alpha-20260801120000..0.2.0-beta-20260901120000'),
      );
    });

    test('and an empty range is said out loud rather than left as a heading', () async {
      final NotesOutcome outcome = await notesOf(
        '0.2.0-stable-20260901130000',
        answers: <String, GitAnswer>{
          'tag --list': const GitAnswer(
            status: 0,
            output: '0.2.0-beta-20260901120000\n0.2.0-stable-20260901130000\n',
          ),
        },
      );

      expect(
        outcome.page,
        contains('Nothing changed since 0.2.0-beta-20260901120000'),
        reason:
            'the same code cut on a riper channel is a real release, and a page showing no changes '
            'would read as a page nobody generated',
      );
    });
  });

  group('how the release is marked', () {
    test('is the ranking of the channel and nothing else', () async {
      for (final (String channel, bool expected) in <(String, bool)>[
        ('alpha', true),
        ('beta', true),
        ('stable', false),
      ]) {
        final NotesOutcome outcome = await notesOf('0.2.0-$channel-20260901120000');

        expect(outcome.isGreen, isTrue, reason: outcome.refusal ?? '');
        expect(
          outcome.isPreRelease,
          expected,
          reason:
              'every tag here carries a hyphen, so a marking read off the text would answer true '
              'for stable as well and tell everyone an alpha was finished',
        );
      }
    });

    test('and a channel nothing ranks refuses rather than guessing', () async {
      final NotesOutcome outcome = await notesOf('0.2.0-gamma-20260901120000');

      expect(outcome.isGreen, isFalse);
      expect(outcome.refusal, contains('gamma'));
      expect(outcome.refusal, contains('alpha, beta, stable'));
    });
  });

  group('what the notes refuse', () {
    test('a tag the workflow would not trigger on', () async {
      final NotesOutcome outcome = await notesOf('master');

      expect(outcome.isGreen, isFalse);
      expect(outcome.refusal, contains(releaseWorkflowPath));
    });

    test('a tree holding no package, which would be a ref carrying nothing', () async {
      final NotesOutcome outcome = await notesOf(
        '0.2.0-beta-20260901120000',
        manifests: ManifestsInMemory(<String, String>{}),
      );

      expect(outcome.isGreen, isFalse);
      expect(outcome.refusal, contains('no package'));
    });

    test(
      'and a history that could not be read, rather than a page saying nothing changed',
      () async {
        final NotesOutcome outcome = await notesOf(
          '0.2.0-beta-20260901120000',
          answers: <String, GitAnswer>{
            'tag --list': const GitAnswer(status: 128, output: 'not a git repository'),
          },
        );

        expect(outcome.isGreen, isFalse);
        expect(outcome.refusal, contains('not a git repository'));
      },
    );
  });
}
