// A test may read the real files; the rule that confines `dart:io` is about the shipped library.
// The programs are the installation's own, and the whole point of this file is to measure the ones
// that ship against the step that fills the file they read.
import 'dart:io';

import 'package:ansiwise_api/ansiwise_api.dart';
import 'package:hostyour_cloud/hostyour_cloud.dart';
import 'package:test/test.dart';

import 'composition.dart';

/// The credentials an operator is asked for and the credentials the seed reads are ONE set.
///
/// **What breaks when they come apart, and why nothing else notices.** `write_stage_secrets` writes
/// `secrets/secrets.<stage>` and refuses to go on without every credential it names there. The seed
/// rows of the programs read that same file back by variable name. Neither side declares the other,
/// so the two names are held together by nothing but somebody typing them the same way twice — and
/// the two ways they come apart fail at opposite ends of an install.
///
/// A variable the seed reads and the step never writes is empty in the file, and the seed refuses by
/// name with `on_failure: exit`: the run stops on a machine that is already carrying an unsealed
/// Vault, at the row that was going to fill it.
///
/// A variable the step writes and no seed row reads is worse, because nothing reports it at all. The
/// operator obtains a credential from a third party, pastes it in, the install comes back green, and
/// the value sits in a file on the machine. Whatever needed it finds nothing in Vault, days later,
/// with a message about the thing it could not do rather than about the credential nobody carried.
///
/// **Three sources, and only one of them is the operator.** A field is filled from the hand-filled
/// input, or generated by the run (`mint`), or supplied by another writer (`fields_owned_elsewhere`).
/// The last two are declared on the row itself, so they are read off the row rather than listed here
/// — a list would be a fourth place to keep in step, which is the defect this file is about.
///
/// **The build plane is the second half.** Its credentials are left out of the hand-filled input of
/// every other cluster, so a row reading one of them must carry the gate that limits it to the
/// cluster carrying the build plane, and a row reading any other must not. Gated wrongly one way the
/// run stops on every cluster but one; the other way the credential is written on one cluster and
/// silently nowhere else.
void main() {
  /// The condition a row carries where it belongs to the cluster carrying the build plane.
  const PredicateName onTheBuildPlane = PredicateName('build_plane_here');

  /// The step that writes one entry of the seed.
  const StepName seedEntry = StepName('vault_kv_entry');

  // The plugins the shipped configuration turns on, composed the way the binary composes them. The
  // rows are read RESOLVED, so a row that leaves `mint` or `fields_owned_elsewhere` out is read with
  // the empty default the step declares — the same value the engine hands the step.
  late final Registry shipped;
  setUpAll(() async => shipped = await shippedRegistry());

  /// Every seed row of every program this installation ships.
  ///
  /// All of them and not `deploy-gitops` alone: a seed row added to another program would otherwise
  /// read a variable this file never sees, and the equality below would go red for a program that is
  /// perfectly correct — or, in the other direction, pass while a second program quietly asks for a
  /// credential nobody is given.
  List<ResolvedStep> seedRows() => <ResolvedStep>[
    for (final File file in Directory(
      '$installationRoot/$installationPrograms',
    ).listSync().whereType<File>().where((File f) => f.path.endsWith('.yaml')))
      ...ProgramResolver(shipped)
          .resolve(loadProgram(file.readAsStringSync(), where: file.uri.pathSegments.last))
          .steps
          .where((ResolvedStep step) => step.entry.step == seedEntry),
  ];

  /// The arguments [row] runs with: what the program wrote, plus the step's own defaults.
  Arguments argumentsOf(ResolvedStep row) {
    final Map<String, Object> defaults = <String, Object>{
      for (final ArgumentSpec spec in row.registered.arguments)
        if (spec.defaultValue case final Object value) spec.name: value,
    };
    return defaults.isEmpty ? row.entry.arguments : row.entry.arguments.withDefaults(defaults);
  }

  /// The variables [row] reads out of the hand-filled input, by the field each one fills.
  ///
  /// A field the run generates and a field another writer owns are left out: neither is read from
  /// that file, so neither is a credential the operator was asked for.
  Map<String, String> variablesOf(ResolvedStep row) {
    final Arguments given = argumentsOf(row);
    final Set<String> elsewhere = <String>{
      ...given.textList('mint'),
      ...given.textList('fields_owned_elsewhere'),
    };
    return <String, String>{
      for (final String declared in given.textList('fields'))
        if (declared.indexOf('=') > 0)
          if (!elsewhere.contains(declared.substring(0, declared.indexOf('=')).trim()))
            declared.substring(0, declared.indexOf('=')).trim(): declared
                .substring(declared.indexOf('=') + 1)
                .trim(),
    };
  }

  /// Every variable the seed reads, split by whether its row belongs to the build plane.
  ({Set<String> everywhere, Set<String> buildPlane}) seeded() {
    final Set<String> everywhere = <String>{};
    final Set<String> buildPlane = <String>{};
    for (final ResolvedStep row in seedRows()) {
      final Set<String> into = row.entry.when.contains(onTheBuildPlane) ? buildPlane : everywhere;
      into.addAll(variablesOf(row).values);
    }
    return (everywhere: everywhere, buildPlane: buildPlane);
  }

  test('there are seed rows to measure', () {
    // Without this the two equalities below could both be satisfied by a tree with no seed at all,
    // if the step ever stopped demanding anything. Empty against empty is not agreement.
    expect(seedRows(), isNotEmpty, reason: 'no program of this installation seeds Vault at all');
    expect(WriteStageSecrets.everyCluster, isNotEmpty);
    expect(WriteStageSecrets.buildPlaneOnly, isNotEmpty);
  });

  test('the credentials every cluster is given are exactly the ones its rows read', () {
    expect(
      seeded().everywhere,
      WriteStageSecrets.everyCluster.keys.toSet(),
      reason:
          'a variable on the left that is not on the right is read by a seed row and written by '
          'nothing, and the run stops at that row with Vault already up; a variable on the right '
          'that is not on the left is a credential the operator obtained and pasted in, that '
          'reaches Vault never and is reported nowhere',
    );
  });

  test('the credentials only the build plane is given are exactly the ones its gated rows read', () {
    expect(
      seeded().buildPlane,
      WriteStageSecrets.buildPlaneOnly.keys.toSet(),
      reason:
          'these are left out of the hand-filled input of every other cluster, so a row reading one '
          'of them without $onTheBuildPlane stops the run on every cluster but one, and a row that '
          'carries $onTheBuildPlane while reading a credential every cluster is given writes it on '
          'one cluster and silently nowhere else',
    );
  });

  test('nothing the run generates or another writer owns is also asked of the operator', () {
    // The other side of leaving those fields out above. A field the run mints is a value nobody can
    // be asked for; a field another writer owns is one nobody here supplies. Asking for either would
    // put a second answer behind one value, and whichever of the two lost would be lost in silence.
    final Set<String> asked = <String>{
      ...WriteStageSecrets.everyCluster.keys,
      ...WriteStageSecrets.buildPlaneOnly.keys,
    };
    for (final ResolvedStep row in seedRows()) {
      final Arguments given = argumentsOf(row);
      final Set<String> elsewhere = <String>{
        ...given.textList('mint'),
        ...given.textList('fields_owned_elsewhere'),
      };
      for (final String declared in given.textList('fields')) {
        final int equals = declared.indexOf('=');
        if (equals <= 0 || !elsewhere.contains(declared.substring(0, equals).trim())) {
          continue;
        }
        expect(
          asked,
          isNot(contains(declared.substring(equals + 1).trim())),
          reason:
              '${given.text('path')} declares ${declared.substring(0, equals).trim()} as filled by '
              'something other than the operator, and the operator is asked for it as well',
        );
      }
    }
  });
}
