import 'package:ansiwise_core/ansiwise_core.dart';

import 'argument_text.dart';
import 'ssh_key.dart';
import 'vault_api.dart';
import 'vault_profile.dart';

/// Mints an ed25519 key pair into one entry of the store, beside the fingerprint of the host key
/// this machine presents.
///
/// **What no other row can write.** The entry a caller needs in order to
/// reach a machine over SSH carries two values, and neither of the two ways a row has of filling an
/// entry can produce them. A hand-filled input is a file of `KEY=value` lines, so it cannot hold a
/// private key, which is many lines. And the generator beside it makes a random value, which is a
/// password rather than half of a key pair — the other half has to match it, and nothing random
/// matches anything. So the entry stood empty, whatever a program declared about it.
///
/// **Both fields, because either alone is useless.** A caller presents the private key AND checks
/// the host against the fingerprint before it hands the key over; given only one of the two it
/// either cannot authenticate or refuses the host it reached. They are one credential and they are
/// written in one act.
///
/// **A KEY PAIR ALREADY IN THE STORE IS NEVER MINTED AGAIN, and this is the decision this step is
/// built around.** The public half of an existing pair stands in the `authorized_keys` of every
/// machine the caller reaches, and nothing here knows which machines those are. Minting a second
/// pair over the first would therefore take away an access this run cannot restore — the caller
/// would present a key no machine has been told about, and every one of them would refuse it. So a
/// value that is there is read, kept, and written back unchanged; only an entry that carries none is
/// given one. Rotating such a key is a deliberate act with its own order — place the new public half
/// everywhere first, then replace the private one — and no step that also runs on an ordinary
/// redeployment may perform it.
///
/// **What cannot be read is refused, never replaced.** An entry holding something under the private
/// key's name that does not parse as an unencrypted ed25519 key is left exactly as it is and the run
/// is blocked. It is either a value another writer owns or a damaged one, and both of those are
/// cases where writing is the one act that cannot be taken back.
///
/// **The fingerprint is measured on every run and replaced when it differs**, which is the opposite
/// rule from the key's and for the opposite reason. It describes the machine as it stands now: a
/// host key regenerated by a reinstall makes the stored value name a host that no longer exists, and
/// a caller comparing against it refuses the connection. Nothing is lost by writing the current one,
/// and reporting the entry as complete while it names the wrong host would be the run claiming a
/// path that does not work.
///
/// **The public half is published**, so the row that places it in an `authorized_keys` file is given
/// exactly what was written here rather than reading the store a second time with a rule of its own.
/// It is published from the check, always out of what the store actually holds — on the run that
/// mints it and on every run afterwards, where it is read back out of the private half.
final class VaultKvSshKeyPair extends IrreversibleStep {
  /// Writes the key pair and the host key fingerprint to [path] on [mount] of this installation's
  /// Vault.
  const VaultKvSshKeyPair({
    required this.repository,
    required this.mount,
    required this.path,
    required this.privateKeyField,
    required this.hostKeyFingerprintField,
    required this.hostKeyPath,
    required this.comment,
    required this.layout,
  });

  /// Builds the step from what the program gave it.
  factory VaultKvSshKeyPair.fromArguments(Arguments arguments) => VaultKvSshKeyPair(
    repository: arguments.text('repository'),
    mount: arguments.text('mount'),
    path: arguments.text('path'),
    privateKeyField: arguments.text('private_key_field'),
    hostKeyFingerprintField: arguments.text('host_key_fingerprint_field'),
    hostKeyPath: arguments.text('host_key_path'),
    comment: arguments.text('comment'),
    layout: VaultLayout.fromArguments(arguments),
  );

  /// What this step accepts.
  static const List<ArgumentSpec> arguments = <ArgumentSpec>[
    ArgumentSpec(
      name: 'repository',
      kind: ArgumentKind.text,
      describes:
          "the checkout this installation runs from, which carries the cluster's own profile and "
          "the credential file Vault's root token was written to",
    ),
    ArgumentSpec(
      name: 'mount',
      kind: ArgumentKind.text,
      describes: 'the key-value mount this entry is written on',
    ),
    ArgumentSpec(
      name: 'path',
      kind: ArgumentKind.text,
      describes:
          'the entry, below the mount — it may carry the slot this row names under run_answer, '
          'where the entry belongs to one value of that axis rather than to all of them',
    ),
    ArgumentSpec(
      name: 'private_key_field',
      kind: ArgumentKind.text,
      describes:
          'the field of that entry the private half is written under. Whatever reads it expects '
          'that name, so it is stated here rather than chosen in this package',
    ),
    ArgumentSpec(
      name: 'host_key_fingerprint_field',
      kind: ArgumentKind.text,
      describes:
          'the field of that entry the fingerprint of this host\'s key is written under, for the '
          'same reason the field above is named here',
    ),
    ArgumentSpec(
      name: 'host_key_path',
      kind: ArgumentKind.text,
      describes:
          'where the PUBLIC half of the host key this machine presents stands, as one line. Its '
          'fingerprint is what a caller compares the key it is offered against, so which of the '
          'host keys a machine carries is meant is a fact of the caller and not of this package',
    ),
    ArgumentSpec(
      name: 'comment',
      kind: ArgumentKind.text,
      describes:
          'the comment the minted key carries, which is what says whose key it is in the '
          '"authorized_keys" file it ends up in — it may carry the slots this family fills, so it '
          'can name the installation the key belongs to',
    ),
    ...VaultLayout.arguments,
  ];

  /// The answers this step reads, which is what its registry entry declares.
  ///
  /// None by name, as everywhere in this family: what varies with the run reaches this step through
  /// the slots the layout fills, and which answer fills them is a value of a program.
  static const List<String> answers = <String>[];

  /// What this step publishes.
  static const List<MeasurementSpec> publishes = <MeasurementSpec>[
    MeasurementSpec(
      name: MeasurementName('ssh_public_key'),
      describes: 'the public half of the key pair the entry holds, as one authorized_keys line',
    ),
  ];

  /// The checkout this installation runs from.
  final String repository;

  /// Where the profile and the credential file stand under the checkout.
  final VaultLayout layout;

  /// The key-value mount.
  final String mount;

  /// The entry below it.
  final String path;

  /// The field of the entry the private half is written under.
  final String privateKeyField;

  /// The field of the entry the host key's fingerprint is written under.
  final String hostKeyFingerprintField;

  /// Where the public half of this machine's own host key stands.
  final String hostKeyPath;

  /// The comment the minted key carries.
  final String comment;

  @override
  String get irreversibleReason =>
      'the key pair written here is the only copy there is: nothing else holds the private half, so '
      'a later write that replaced it would leave every machine carrying the public one reachable '
      'by nobody. A write becomes the current value and pushes the previous one into a history ten '
      'deep, and past that there is nothing to go back to';

  @override
  Future<CheckResult> check(StepContext context) async {
    final _Entry entry = await _entry(context);
    if (entry.refusal case final String refusal) {
      return CheckResult.blocked(refusal);
    }
    final _Fingerprint host = await _hostKeyFingerprint(context);
    if (host.refusal case final String refusal) {
      return CheckResult.blocked(refusal);
    }
    final String fingerprint = host.value ?? '';

    final HttpAnswer answer = await context.http.send(
      vaultRead(entry.url, entry.dataPath, token: entry.token),
    );
    // TOLD APART, because "I could not read it" is not an answer about what the entry holds. Read as
    // work to do, it sends the run into an apply that mints over a key pair that is already in use.
    final VaultReading reading = readingOf(answer, path: entry.dataPath);
    if (reading case final VaultUnreadable refused) {
      return CheckResult.blocked(refused.because);
    }
    if (reading is! VaultHeld) {
      return const CheckResult.ready();
    }
    final Object? held = reading.data['data'];
    final Map<String, Object?> standing = held is Map<String, Object?>
        ? held
        : const <String, Object?>{};

    final Object? privateKey = standing[privateKeyField];
    if (privateKey is! String || privateKey.isEmpty) {
      context.log.debug('${entry.dataPath} carries no $privateKeyField yet');
      return const CheckResult.ready();
    }
    final String? publicKey = sshPublicKeyIn(privateKey);
    if (publicKey == null) {
      return CheckResult.blocked(
        '$privateKeyField of ${entry.dataPath} is not an unencrypted ed25519 key this can read, and '
        'a value that cannot be read is not a value that may be replaced — whatever holds the '
        'public half matching it would be locked out by the write. Look at that entry before this '
        'runs again',
      );
    }
    context.measurements.publish(const MeasurementName('ssh_public_key'), publicKey);

    if (standing[hostKeyFingerprintField] != fingerprint) {
      // The field, never the value on either side. Which of them is standing there is what an
      // operator would compare by hand, and it is a fact about this host rather than a credential —
      // but a refusal that printed both would be read as an invitation to copy one of them.
      context.log.debug(
        '${entry.dataPath} names a different $hostKeyFingerprintField than $hostKeyPath does',
      );
      return const CheckResult.ready();
    }
    return CheckResult.satisfied(
      '${entry.dataPath} holds a key pair and the fingerprint of the host key at $hostKeyPath',
    );
  }

  @override
  Future<StepPlan> plan(StepContext context) async {
    final _Entry entry = await _entry(context);
    if (entry.refusal case final String refusal) {
      return StepPlan.nothing(refusal);
    }
    return StepPlan.request(
      'POST',
      '${entry.url}/v1/${entry.dataPath}',
      body:
          'the fields $privateKeyField and $hostKeyFingerprintField, the first minted here where '
          'the entry carries none and kept where it does',
    );
  }

  @override
  Future<void> apply(StepContext context) async {
    final _Entry entry = await _entry(context);
    if (entry.refusal case final String refusal) {
      throw StateError(refusal);
    }
    final _Fingerprint host = await _hostKeyFingerprint(context);
    if (host.refusal case final String refusal) {
      throw StateError(refusal);
    }
    final String fingerprint = host.value ?? '';

    final HttpAnswer answer = await context.http.send(
      vaultRead(entry.url, entry.dataPath, token: entry.token),
    );
    final VaultReading reading = readingOf(answer, path: entry.dataPath);
    if (reading case final VaultUnreadable refused) {
      throw StateError(refused.because);
    }
    final Object? held = reading is VaultHeld ? reading.data['data'] : null;
    final Map<String, Object?> standing = held is Map<String, Object?>
        ? held
        : const <String, Object?>{};

    final Object? already = standing[privateKeyField];
    final String privateKey;
    if (already is String && already.isNotEmpty) {
      if (sshPublicKeyIn(already) == null) {
        throw StateError(
          '$privateKeyField of ${entry.dataPath} is not an unencrypted ed25519 key this can read, '
          'and minting over it would lock out whatever holds the public half matching it',
        );
      }
      privateKey = already;
    } else {
      final SshKeyPair minted = await mintedSshKeyPair(
        seed: context.entropy.hex(ed25519KeyBytes),
        check: context.entropy.hex(sshCheckBytes),
        comment: entry.comment,
      );
      privateKey = minted.privateKey;
    }

    // A write to this store replaces the whole entry, so every field it already carries is written
    // back as it stands. Only the two this step owns are decided here.
    final Map<String, Object?> writing = <String, Object?>{
      ...standing,
      privateKeyField: privateKey,
      hostKeyFingerprintField: fingerprint,
    };
    final HttpAnswer written = await context.http.send(
      vaultWrite(
        entry.url,
        entry.dataPath,
        token: entry.token,
        body: <String, Object?>{'data': writing},
      ),
    );
    if (!written.ok) {
      throw RequestRefused(
        method: 'POST',
        url: '${entry.url}/v1/${entry.dataPath}',
        status: written.status,
        body: written.body,
      );
    }
  }

  /// Where this entry stands and what may reach it, or why nothing can.
  Future<_Entry> _entry(StepContext context) async {
    final VaultProfile vault = await vaultProfileFrom(context, repository, layout: layout);
    if (vault.refusal case final String refusal) {
      return _Entry.unreachable(refusal);
    }
    final ArgumentText at = vault.forThisInstallation(context, path);
    if (at.refusal case final String refusal) {
      return _Entry.unreachable(refusal);
    }
    final ArgumentText named = vault.forThisInstallation(context, comment);
    if (named.refusal case final String refusal) {
      return _Entry.unreachable(refusal);
    }
    final RootToken token = await rootTokenFrom(
      context,
      vaultCredentialsPath(context, repository, layout: layout),
    );
    if (token.refusal case final String refusal) {
      return _Entry.unreachable(refusal);
    }
    return _Entry.at(
      url: vault.url ?? '',
      dataPath: '$mount/data/${at.value ?? ''}',
      token: token.value ?? '',
      comment: named.value ?? '',
    );
  }

  /// The fingerprint of the host key at [hostKeyPath], or why it cannot be had.
  ///
  /// Refused rather than left out. A run that wrote the private half and no fingerprint would leave
  /// the entry half-written, and whatever reads it would present a key to a host it cannot verify —
  /// which is the one thing the fingerprint is there to stop.
  Future<_Fingerprint> _hostKeyFingerprint(StepContext context) async {
    if (!await context.files.exists(hostKeyPath)) {
      return _Fingerprint.unreadable(
        '$hostKeyPath is not on this host, and it is where the public half of the host key this '
        'machine presents stands — whatever reaches this machine compares the key it is offered '
        'against the fingerprint of that file',
      );
    }
    final String content = await context.files.read(hostKeyPath);
    final String? fingerprint = sshFingerprintOf(content);
    return fingerprint == null
        ? _Fingerprint.unreadable(
            '$hostKeyPath does not carry a public key line — an algorithm, the key in base64, and a '
            'comment after it. A fingerprint taken of anything else would name no host at all',
          )
        : _Fingerprint.read(fingerprint);
  }
}

/// Where one entry stands, what reaches it, and what the key it carries is called.
final class _Entry {
  const _Entry.at({
    required this.url,
    required this.dataPath,
    required this.token,
    required this.comment,
  }) : refusal = null;

  const _Entry.unreachable(this.refusal) : url = '', dataPath = '', token = '', comment = '';

  /// Where Vault answers.
  final String url;

  /// The entry's data path under Vault's version one API.
  final String dataPath;

  /// The root token every call of this step is made with.
  final String token;

  /// The comment a minted key carries, with this installation's own names in it.
  final String comment;

  /// Why none of the above can be had, or null when it can.
  final String? refusal;
}

/// The fingerprint of this host's key, or why it could not be taken.
final class _Fingerprint {
  const _Fingerprint.read(String this.value) : refusal = null;

  const _Fingerprint.unreadable(String this.refusal) : value = null;

  /// The fingerprint, or null when there is none to be had.
  final String? value;

  /// Why there is none, or null when there is.
  final String? refusal;
}
